### ISSUE TITLE
Epic: Auto Detect Opensearch Version

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#120]
Tasks:
- [x] #121
- [x] https://github.com/grafana/grafana/issues/66318
- [x] https://github.com/grafana/opensearch-datasource/issues/131
- [x] https://github.com/grafana/opensearch-datasource/issues/132
- [x] https://github.com/grafana/opensearch-datasource/issues/170

**Notes:**

We should implement a feature for opensearch that automatically detects the region. Running a get request to the url (with no query parameters) will return a version object:
'''
{
  "name" : "15ffcf528ee3",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "1vbTN7ROS4Sw-8mHbTAIVQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.6.0",
    "build_type" : "tar",
    "build_hash" : "7203a5af21a8a009aece1474446b437a3c674db6",
    "build_date" : "2023-02-24T18:58:37.352296474Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
'''
We can use this to fetch and set the version automatically.

**Comment by fridgepoet** [comment]
Closing this as done, please re-open if that's not the case!
