### ISSUE TITLE
BE: Build query for requesting Node Graph data for a map of all services

### ISSUE THREAD

**Issue by idastambuk** [grafana/opensearch-datasource#332]
If the nodeGraph flag is true, we should add aggregations to the query builder on the backend where we add the traces. There's another task for adding the query for trace spans (for one trace), but the aggregations will most likely be the same as with all services vs one trace. 

We will have to combine aggregations from the below examples into one request with aggregations. We're building and sending a separate request from the trace spans request, as decided in the design doc. 

**Aggregations we have to build for this are:**
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/opensearch-datasource/issues/371
- [ ] https://github.com/grafana/opensearch-datasource/issues/370
- [ ] Get resource and target domains for calculating nodes and edges in response processing ([example](https://docs.google.com/document/d/1czRzu9Z4kWCau_cTUF3ILi2jL3DO02Y-hCHqZFS-JWQ/edit#heading=h.aajoivgbc4oc))
- [ ] Get service throughput and latency ([example](https://docs.google.com/document/d/1czRzu9Z4kWCau_cTUF3ILi2jL3DO02Y-hCHqZFS-JWQ/edit#heading=h.mrg7jb2m16s)).
- [ ] Get error rate for services ([example](https://docs.google.com/document/d/1czRzu9Z4kWCau_cTUF3ILi2jL3DO02Y-hCHqZFS-JWQ/edit#heading=h.zgy57aojigj5))
- [ ] Get target resources in order to display operationNames for each node ([example](https://docs.google.com/document/d/1czRzu9Z4kWCau_cTUF3ILi2jL3DO02Y-hCHqZFS-JWQ/edit#heading=h.1xfmojbizp4b))
```
